name: diary_log
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: 
  hive: 
  hive_flutter: 
  pdf:
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_ui_auth: ^1.9.1
  firebase_ui_oauth_google: ^1.2.13
  image_picker: ^1.0.4
  firebase_storage: ^11.5.0
  path_provider: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: 
  build_runner: 

flutter:
  uses-material-design: true
