// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdrhp9f5IsnrVajZwdk9fi29db_VGk7Ds',
    appId: '1:947264758008:web:0ddff9956da7f4f3839b0d',
    messagingSenderId: '947264758008',
    projectId: 'diary-log-d8379',
    authDomain: 'diary-log-d8379.firebaseapp.com',
    storageBucket: 'diary-log-d8379.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xQADeriMy2S3q6OVSEhq3XqMx_STrgo',
    appId: '1:947264758008:android:3f0d19e6800d37d0839b0d',
    messagingSenderId: '947264758008',
    projectId: 'diary-log-d8379',
    storageBucket: 'diary-log-d8379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApsIpCB7aQgJrlK1VnsVZahPncJiir6cs',
    appId: '1:947264758008:ios:3adb422a15c28b8b839b0d',
    messagingSenderId: '947264758008',
    projectId: 'diary-log-d8379',
    storageBucket: 'diary-log-d8379.appspot.com',
    iosClientId: '947264758008-goq35gjgfrjcsf17b62a6mtsth9d21c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApsIpCB7aQgJrlK1VnsVZahPncJiir6cs',
    appId: '1:947264758008:ios:b8030ad33bae36f0839b0d',
    messagingSenderId: '947264758008',
    projectId: 'diary-log-d8379',
    storageBucket: 'diary-log-d8379.appspot.com',
    iosClientId: '947264758008-kds55mcctfmidffs7kdegf8en7cgklml.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment22.RunnerTests',
  );
}
